# Generated by Django 3.1.6 on 2021-03-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210315_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='awards',
            field=models.ManyToManyField(to='book.Award'),
        ),
    ]
