# Generated by Django 3.1.6 on 2021-03-15 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210315_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_for_this_book', to='book.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='book.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='awards',
            field=models.ManyToManyField(blank=True, to='book.Award'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, choices=[('4', 'Outstanding'), ('3', 'Good'), ('2', 'Not good'), ('1', 'Bad')], max_length=1, null=True),
        ),
    ]
